"""initial schema

Revision ID: 2b42eeb81cf2
Revises: 
Create Date: 2026-03-01 11:57:25.421253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b42eeb81cf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('accuracy', sa.Float(), nullable=True))
        batch_op.drop_column('location_lng')
        batch_op.drop_column('description')
        batch_op.drop_column('photo')
        batch_op.drop_column('location_lat')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('location_lat', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('location_lng', sa.FLOAT(), nullable=True))
        batch_op.drop_column('accuracy')
        batch_op.drop_column('location_name')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
